### ISSUE TITLE
Feature Request: Proxy support

### ISSUE THREAD

**Issue by curby** [vitorgalvao/notificator#1]
The script fails when a proxy is configured in macOS System Preferences, and is required for Internet access.

**Comment by vitorgalvao** [comment]
I see no reason why that should happen, and I can’t reproduce. The setup script makes [two `curl` calls](https://github.com/vitorgalvao/notificator/blob/master/setup_notificator#L74L76): one to know what to get, and the other to get it.

You can copy the script to your machine and edit those two lines to use your proxy configuration. That script is stable and unlikely to change, so there’s little risk of it becoming outdated. I might add an option for codesigning, but it’s unlikely I’ll add anything else.
