### ISSUE TITLE
how to properly add notificator?:)

### ISSUE THREAD

**Issue by seekerPL** [vitorgalvao/notificator#2]
Hi, 
Sorry for the silly question, but can anyone advise how to properly add notificator to Alfred's workflow?

**Comment by vitorgalvao** [comment]
Add the script anywhere you want inside the Workflow’s directory and [call it](https://github.com/vitorgalvao/notificator#usage) with Bash, or Zsh, or from whichever language you’re using.

Unless you’re building a Workflow with code, use [Alfred’s native object](https://www.alfredapp.com/help/workflows/outputs/post-notification/).
