### ISSUE TITLE
Add support for contentImage, Reply, Dropdown Actions

### ISSUE THREAD

**Issue by joeynotjoe** [vitorgalvao/notificator#3]
First off, I just want to say that Notificator is really awesome. No more telling people to run `brew install terminal-notifier` :) I think that it would be even better if it had [terminal-notifier's](https://github.com/julienXX/terminal-notifier) "contentImage" function, as well as [alerter's](https://github.com/vjeantet/alerter) Reply and Dropdown options. I realize that's asking a lot, but it would be really powerful to have those things. Thanks, happy new year 🥂

**Comment by vitorgalvao** [comment]
Unfortunately those aren’t available to AppleScript/JXA notifications, which the script uses. But even if I were to rewrite it:

If I recall correctly (haven’t looked at it in years), forcing a notification to display as an alert requires an entitlement, which means signing the app with a developer ID, which means doing it beforehand, which means no custom image, which is the goal of Notificator.

Terminal-notifier’s contentImage uses a private API, which I want to avoid.

The other request I’ll still look into it. Happy New Year!

**Comment by joeynotjoe** [comment]
This explains why you didn't implement these from the start 😂
Thank you!
