### ISSUE TITLE
Allow modification of action upon clicking notification

### ISSUE THREAD

**Issue by joeynotjoe** [vitorgalvao/notificator#4]
Right now, any notification I click takes me to this GitHub page. Can we add another flag like `--open` to allow users to customize that action?

**Comment by vitorgalvao** [comment]
Ultimately I’m deciding against adding the feature. Adding a way to run a bespoke command is [also not supported](https://github.com/vitorgalvao/notificator/issues/3) and working around it opens other cans of worms, requiring sanitising input and worrying about malicious commands. It would be a very hacky solution which would make maintenance harder, for a feature which isn’t requested often.

Thank you for the feature request anyway. I am open to doing something different (but still fixed) when the notification is clicked, but it’s not a priority.

**Comment by joeynotjoe** [comment]
That makes sense. Bummer, but understandable!
