### ISSUE TITLE
Forbidden sign over notifications?

### ISSUE THREAD

**Issue by denisbr** [vitorgalvao/notificator#5]
<img width="328" alt="SCR-20230419-ktlr" src="https://user-images.githubusercontent.com/478790/233038840-deaa983c-99f7-4c7e-8e16-663ac6a675c9.png">

After an update of MacOS, something has changed and all my notifications that use notificator have this forbidden mark across the original icon. I tried to flip the notifications enabled switch for Alfred, but this did not help. Any ideas what can cause this and how to fix it?

**Comment by vitorgalvao** [comment]
System Settings → Notifications. Find it on the list (the specific Notificator instances, not Alfred) then right-click → Reset Notifications…
