### ISSUE TITLE
Dialog box with "Press Run to run this script, or Quit to quit."

### ISSUE THREAD

**Issue by vdesabou** [vitorgalvao/notificator#7]
Hey @vitorgalvao , I'm using your tool but sometimes we see this dialog popping up
See https://github.com/vdesabou/alfred-spotify-mini-player/issues/611

Any idea why ?

**Comment by vitorgalvao** [comment]
The good news is that I know why it happens. The dialog pops up if <kbd>⌃</kbd> (ctrl) is pressed at the time the app is run. You can try it easily by holding it down before a notification shows.

The bad news is that I searched for it many years back and found no way to prevent that. It’s an AppleScript app thing. In the past I even tried various tricks such as detecting if <kbd>⌃</kbd> was held down before the script was run and delaying it until it was released, but ultimately I could still trigger, it’ll always be a timing matter.
